# Generated by Django 6.1.1 on 2026-10-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('items_per_carton', models.IntegerField(help_text='How many single pieces fit into one carton?')),
                ('price_per_carton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pieces_in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cartons_taken', models.IntegerField(default=0)),
                ('pieces_taken', models.IntegerField(default=0)),
                ('cartons_returned', models.IntegerField(default=0)),
                ('pieces_returned', models.IntegerField(default=0)),
                ('cash_owed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promoter')),
            ],
        ),
    ]
