# Generated by Django 6.1.1 on 2026-10-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cartons_in_stock',
            field=models.IntegerField(default=0, help_text='Number of full unopened cartons in warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='pieces_in_stock',
            field=models.IntegerField(default=0, help_text='Number of remaining loose pieces in warehouse'),
        ),
        migrations.AlterField(
            model_name='dailydeployment',
            name='cash_owed',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_pieces_in_stock',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
