# Generated by Django 6.1.1 on 2026-10-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_cartons_in_stock_product_pieces_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cartons_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
