# Generated by Django 6.1.1 on 2026-10-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_initial_stock_alter_product_cartons_in_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_date', models.DateField(db_index=True)),
                ('event_type', models.CharField(choices=[('dispatch', 'Dispatched Out'), ('return', 'Returned — Not Sold'), ('correction', 'Correction'), ('delete', 'Deleted Mistake')], db_index=True, max_length=20)),
                ('promoter_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('cartons', models.IntegerField(default=0)),
                ('pieces', models.IntegerField(default=0)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('label', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
