# Generated by Django 6.1.1 on 2026-10-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_shop_activitylog_shop_dailydeployment_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='dailydeployment',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
