# Generated by Django 6.1.1 on 2026-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shop_activitylog_shop_dailydeployment_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='pin',
            field=models.CharField(default=0, help_text='4-digit PIN for promoter login', max_length=4),
            preserve_default=False,
        ),
    ]
