# Generated by Django 6.1.1 on 2026-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_promoter_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
